<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
      <ProjectReference Include="..\RCommerce.Infrastructure\RCommerce.Infrastructure.csproj" />
      <ProjectReference Include="..\DScannerLibrary\DScannerLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Security.Permissions" Version="8.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="Mapster.DependencyInjection" Version="1.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0-rc.2.23480.2" />
    <PackageReference Include="Microsoft.Identity.Web" Version="2.15.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="6.5.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="6.5.0" />
    <PackageReference Include="PayPal" Version="1.9.1" />
  </ItemGroup>
</Project>
